### PR TITLE
In infinite mode, pagedCollection.url can be a function

### PR DESCRIPTION
**Pull request by duhast**

### CODE REVIEW

**Comment by wyuenho** [comment]
Thanks for the PR. If you can write a test case for this I'll merge as soon as possible.

**Comment by duhast** [comment]
@wyuenho, unfortunately i'm not a guru of writing tests for NodeJS, but i'll try once i'll have time.

**Comment by wyuenho** [comment]
You can take a look at the existing tests now. The existing tests are using QUnit. It should be pretty easy.

**Comment by wyuenho** [comment]
Fixed in issue #50.

**Pull request closed without merging**
