### PR TITLE
Explicit Check for XHR

### PR DESCRIPTION
**Pull request by josx**
I am using backbone-pageable (it's great), but **not using XHR** at all. 
My backbone collections sync via Socket.io, so every time try to parselink gives me Errors.
**So I have added just an if checking explicitly for XHR**, before:
`var linkHeader = options.xhr.getResponseHeader("Link");`

This can help others to avoid this problem

### CODE REVIEW

**Comment by wyuenho** [comment]
How do you get the infinite pagination links from Socket.io now? Would it make more sense to just override parseLinks in your code to return an empty hash? I suspect that most people will use XHR.

**Comment by josx** [comment]
I am trying to make it work, but i dont understand very well how to do it.
Also the infite pagination example it is not working.

To avoid error we can return a empty hash (It is what is doing with this code).

**Comment by josx** [comment]
On infine mode I need to getNextPage() on scrolling until there is no more data. (also as i told you i cant send link headers, so i cant send last page). How can I accomplish this?  
Thanks a lot

**Comment by wyuenho** [comment]
You can embed the links in the response body as some JSON attributes. Pagination data should always be sent down from the server. I don't understand how pushing from Socket.io come into play with pagination. You can do whatever you want to `parseLinks`. All the parameters necessary for parsing links is given to `parseLinks`. You just have to keep the signature.

**Pull request closed without merging**
